# Generated by Django 5.0.6 on 2024-05-24 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_remove_job_user_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="resumes",
        ),
        migrations.DeleteModel(
            name="Job_Resume",
        ),
    ]
