[tool.poetry]
name = "EngiLink"
version = "0.1.0"
description = ""
authors = ["andyhuangdev <ah052691@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.4"
mysqlclient = "^2.2.4"
python-dotenv = "^1.0.1"
<<<<<<< HEAD
django-crispy-forms = "^2.1"
crispy-tailwind = "^1.0.3"
=======

>>>>>>> 220bdc9 (fix: remove sweetify)

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
