# Generated by Django 5.0.4 on 2024-05-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("N", "不透露")], max_length=1
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1年以下", "一年以下"),
                            ("3年以下", "三年以下"),
                            ("3年以上", "三年以上"),
                            ("5年以上", "五年以上"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Python", "Python"),
                            ("JavaScript", "JavaScript"),
                            ("Java", "Java"),
                            ("C++", "C++"),
                            ("HTML/CSS", "HTML/CSS"),
                            ("PHP", "PHP"),
                            ("Ruby", "Ruby"),
                            ("Swift", "Swift"),
                            ("其他", "其他"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("account", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("1", "高中職以下"),
                            ("2", "高中職"),
                            ("3", "專科"),
                            ("4", "學士"),
                            ("5", "碩士"),
                            ("6", "博士"),
                            ("7", "肄業"),
                        ],
                        max_length=1,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resume.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("responsibility", models.CharField(max_length=200)),
                (
                    "technologies_used",
                    models.CharField(
                        choices=[
                            ("Python", "Python"),
                            ("JavaScript", "JavaScript"),
                            ("Java", "Java"),
                            ("C++", "C++"),
                            ("HTML/CSS", "HTML/CSS"),
                            ("PHP", "PHP"),
                            ("Ruby", "Ruby"),
                            ("Swift", "Swift"),
                            ("其他", "其他"),
                        ],
                        max_length=200,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resume.profile"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resume.user"
            ),
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resume.profile"
                    ),
                ),
            ],
        ),
    ]
