# Generated by Django 5.0.4 on 2024-05-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_education_is_deleted_profile_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="profile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
