# Generated by Django 5.0.4 on 2024-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0003_remove_profile_is_deleted_profile_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="work",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="education",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
