# Generated by Django 5.0.4 on 2024-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0004_remove_education_is_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="skills",
        ),
        migrations.AlterField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(
                choices=[
                    ("Python", "Python"),
                    ("JavaScript", "JavaScript"),
                    ("Java", "Java"),
                    ("C++", "C++"),
                    ("HTML/CSS", "HTML/CSS"),
                    ("PHP", "PHP"),
                    ("Ruby", "Ruby"),
                    ("Swift", "Swift"),
                    ("其他", "其他"),
                ],
                to="resume.skill",
            ),
        ),
    ]
