# Generated by Django 5.0.4 on 2024-05-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0006_remove_profile_skills_delete_skill_profile_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Python", "Python"),
                            ("JavaScript", "JavaScript"),
                            ("Java", "Java"),
                            ("C++", "C++"),
                            ("HTML/CSS", "HTML/CSS"),
                            ("PHP", "PHP"),
                            ("Ruby", "Ruby"),
                            ("Swift", "Swift"),
                            ("其他", "其他"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="skills",
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(to="resume.skill"),
        ),
    ]
