# Generated by Django 5.0.4 on 2024-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0007_skill_remove_profile_skills_profile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                choices=[(1, "Python"), (2, "JavaScript"), (3, "Java")], max_length=100
            ),
        ),
    ]
