# Generated by Django 5.0.4 on 2024-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_alter_skill_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                choices=[
                    ("Python", "Python"),
                    ("JavaScript", "JavaScript"),
                    ("Java", "Java"),
                    ("C++", "C++"),
                    ("HTML/CSS", "HTML/CSS"),
                    ("PHP", "PHP"),
                    ("Ruby", "Ruby"),
                    ("Swift", "Swift"),
                    ("其他", "其他"),
                ],
                max_length=100,
            ),
        ),
    ]
