# Generated by Django 5.0.4 on 2024-05-02 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0010_remove_profile_skills_delete_skill_profile_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="skills",
        ),
    ]
