# Generated by Django 5.0.4 on 2024-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0011_remove_profile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("男", "男"), ("女", "女"), ("不透露", "不透露")], max_length=3
            ),
        ),
    ]
