# Generated by Django 5.0.4 on 2024-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0012_alter_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "男"), ("F", "女"), ("N", "不透露")], max_length=1
            ),
        ),
    ]
