# Generated by Django 5.0.4 on 2024-05-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0013_alter_profile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(blank=True, to="resume.skill"),
        ),
    ]
