# Generated by Django 5.0.4 on 2024-05-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0015_remove_profile_skills_delete_skill_profile_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="work",
            name="profile",
        ),
        migrations.AddField(
            model_name="profile",
            name="company_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="degree",
            field=models.CharField(
                choices=[
                    ("1", "高中職以下"),
                    ("2", "高中職"),
                    ("3", "專科"),
                    ("4", "學士"),
                    ("5", "碩士"),
                    ("6", "博士"),
                    ("7", "肄業"),
                ],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="education_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="education_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="major",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="project_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="responsibility",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="school_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="technologies_used",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Work",
        ),
    ]
