# Generated by Django 5.0.6 on 2024-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
