# Generated by Django 5.0.6 on 2024-05-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0003_education_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="position",
            new_name="posit",
        ),
    ]
